#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

class Receiver:
    
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)
        self.sender_sn = 0;
        self.sn = 0;
        self.ack_id = 0
        self.remote_host = None
        self.remote_port = None

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.remote_host, self.remote_port))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                data, addr = conn.recvfrom(65535)

                # Grab the remote host/port if we don't alreadt have it
                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]

                msg = json.loads(data.decode('utf-8'))

                if (len(msg['data'].encode('utf-8')) + self.sender_sn) == msg['sn']: 
                    self.log("Received data message %s" % msg)
                    self.sender_sn = msg['sn']
                    print(msg["data"], end='', flush=True)

                
                self.send({ "type": "ack", "sender_sn": msg['sn'], "id":self.ack_id})
                self.ack_id+=1
                #else:
                    #self.log("message not proccessed with sn num: %s" % msg['sn'])
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()


                #if (len(msg['data'].encode('utf-8')) + self.sender_sn) >= msg['sn']: 
                    # if its greater than or equal to, then we want to add the message to a buffer. Then loop the buffer and see if we can send anything
